### ISSUE TITLE
Failed to compile with golang 1.15

### ISSUE THREAD

**Issue by 1715173329** [txthinking/brook#740]
Hi, I tried to compile it under golang 1.15, but it threw the following erros, is it possible to fix this?
```bash
$ go version
go version go1.15.6 linux/amd64

$ go get -t -v .
_/brook
# _/brook
./client.go:38:36: not enough arguments in call to socks5.NewClassicServer
	have (string, string, string, string, int, int)
	want (string, string, string, string, int, int, int, int)
./client.go:123:13: s.UDPSrc undefined (type *socks5.Server has no field or method UDPSrc)
./client.go:131:17: Dial.DialUDP undefined (type x.Dialer has no field or method DialUDP)
./client.go:141:4: s.UDPSrc undefined (type *socks5.Server has no field or method UDPSrc)
./client.go:159:33: s.UDPTimeout undefined (type *socks5.Server has no field or method UDPTimeout)
./dns.go:351:17: Dial.DialUDP undefined (type x.Dialer has no field or method DialUDP)
./map.go:216:17: Dial.DialUDP undefined (type x.Dialer has no field or method DialUDP)
./packetclient.go:45:9: undefined: x.BP65507
./packetclient.go:46:9: undefined: x.BP65507
./packetclient.go:73:8: undefined: x.BP32
./packetclient.go:73:8: too many errors

$ cd cli/brook; go build -ldflags '-s -w'
# _/brook/cli/brook
./main.go:98:30: not enough arguments in call to brook.NewServer
	have (string, string, int, int)
	want (string, string, int, int, int)
./main.go:145:31: not enough arguments in call to brook.NewServer
	have (string, string, int, int)
	want (string, string, int, int, int)
./main.go:209:30: not enough arguments in call to brook.NewClient
	have (string, string, string, string, int, int)
	want (string, string, string, string, int, int, int, int)
./main.go:265:15: undefined: brook.NewMap
./main.go:331:27: not enough arguments in call to brook.NewDNS
	have (string, string, string, string, string, string, int, int)
	want (string, string, string, string, string, string, int, int, int)
./main.go:397:30: not enough arguments in call to brook.NewTproxy
	have (string, string, string, int, int)
	want (string, string, string, int, int, int)
./main.go:468:32: not enough arguments in call to brook.NewWSServer
	have (string, string, string, string, int, int)
	want (string, string, string, string, int, int, int)
./main.go:525:32: not enough arguments in call to brook.NewWSClient
	have (string, string, string, string, int, int)
	want (string, string, string, string, int, int, int, int)
./main.go:563:27: too many arguments in call to brook.Link
	have (string, string, string)
	want (string, string)
./main.go:592:13: too many arguments in call to brook.QR
	have (string, string, string)
	want (string, string)
./main.go:592:13: too many errors
```
